[WindTunnelApp]
name = "WindTunnelApp"
version = "0.1.0"
description = "Viewer for wind tunnel data"
dependencies = [
    "pandas",
    "numpy",
    "openpyxl",
    "streamlit",
    "sqlite3",
    "plotly"
]
